from turtle import Turtle,title
root=Turtle()
root.forward(100)
root.penup()
root.setposition(0,0)
root.pendown()
root.left(90)
root.forward(100)
root.penup()
root.setposition(0,0)
root.pendown()
root.left(180)
root.forward(100)
root.penup()
root.setposition(0,0)
root.pendown()
root.left(270)
root.forward(100)
root.penup()
root.setposition(0,50)
root.pendown()
root.circle(50)
root.penup()
root.setposition(0,110)
root.pendown()




root.getscreen()._root.mainloop()